# Common configuration sections for DeepSeek models
_common_deepseek_model_cfgs: &common_deepseek_model_cfgs
  inference_backend: api
  model_sdk_type: openai
  api_key_name: DEEPSEEK_API_KEY

_common_deepseek_inference_cfgs: &common_deepseek_inference_cfgs
  max_tokens: 8192
  max_retry: 3
  max_workers: 32
  sleep_seconds: 30
  timeout: 300

_common_deepseek_cache_cfgs: &common_deepseek_cache_cfgs
  cache_type: redis
  json_dir: null
  redis_cfgs:
    host: localhost
    port: 6379
    db: 0
    password: password
  force_update: false

# Complete configuration for deepseek-chat
deepseek-chat:
  model_cfgs:
    <<: *common_deepseek_model_cfgs
    model_name_or_path: deepseek-chat
  inference_cfgs:
    <<: *common_deepseek_inference_cfgs
  cache_cfgs:
    <<: *common_deepseek_cache_cfgs

# Complete configuration for deepseek-reasoner
deepseek-reasoner:
  model_cfgs:
    <<: *common_deepseek_model_cfgs
    model_name_or_path: deepseek-reasoner
  inference_cfgs:
    <<: *common_deepseek_inference_cfgs
  cache_cfgs:
    <<: *common_deepseek_cache_cfgs
